user1 = User.create(:username => "ada", :password => "123")
user2 = User.create(:username => "taz", :password => "321")
user3 = User.create(:username => "tripp", :password => "password")
user4 = User.create(:username => "melissa", :password => "password")

recipeType1=RecipeType.create(:name=>"Breakfast")
recipeType1=RecipeType.create(:name=>"Lunch")
recipeType1=RecipeType.create(:name=>"Dinner")
recipeType1=RecipeType.create(:name=>"Snack")
recipeType1=RecipeType.create(:name=>"Dessert")




# breakfast
recipe1=Recipe.create(:name=>"Blueberry dog food", :ingredients=>"*dog food *blueberries", :steps=>"*put dog food in bowl *add blueberries and mix in" ,:description=>"A quick way to add some extra vitamins to your dog food.", :user_id=> 2, :recipe_type_id=>1)
recipe2=Recipe.create(:name=>"Breakfast Bowl", :ingredients=>"*eggs *shreaded hash browns *cheese *bacon", :steps=>"*cut up bacon and cook *cook hash browns *scramble eggs in bowl *cook eggs *combine all together and top with cheese" ,:description=>"A quick tasty breakfast thats great for the morning after a big night out!", :user_id=> 3, :recipe_type_id=>1)
recipe3=Recipe.create(:name=>"Easy, Three Ingredient Cinnamon Rolls", :ingredients=>"*1 bag Rhodes Cinnamon Rolls (12 count - frozen) *1 box Cook & Serve Vanilla Pudding *1 stick of butter", :steps=>"*Spray 9x13 baking dish with cooking spray. Line dish with frozen cinnamon rolls. * Sprinkle pudding mix over the top of the cinnamon rolls. Melt stick of butter & drizzle on top. * Cover dish with saran wrap. Be sure to spray saran wrap with cooking spray to prevent sticking. Refrigerate overnight. * In the morning, set the cinnamon rolls out at room temperature for 45min - 1 hour prior to allow rolls to rise. * Preheat oven to 350 degrees & bake for 20 minutes. Ice while hot." ,:description=>"*Healthy or not, I’ve come to the conclusion that they are worth every single calorie! Even if I have to do an extra hour of Zumba to burn them off! ", :user_id=> 4, :recipe_type_id=>1)
recipe20=Recipe.create(:name=>"Homemade Dog Food Recipe", :ingredients=>"*1 (16-ounce) can chicken or use leftovers *1 1/2 cups brown rice *1 (15-ounce) can beans, drained and rinsed *1 1/2 cups chopped carrots or baby carrots *1/2 – 1 cup peas, frozen or canned *1/2 cup green lentils", :steps=>"*Stir in ground beef, brown rice, kidney beans, butternut squash, carrots, peas and 4 cups water into a 6-qt slow cooker. *Cover and cook on low heat for 5-6 hours or high heat for 2-3 hours, stirring as needed. *Let cool completely. *Note – I used white rice since it’s all I had. White also helps when your dog is having digestive issues especially in puppies." ,:description=>"Easy Homemade Breakfast for Dogs can be cooked on the stove or in a slow cooker and lasts for days.", :user_id=> 1, :recipe_type_id=>1)

# lunch
recipe4=Recipe.create(:name=>"Ham Sandwich", :ingredients=>"*Bread *Ham *Cheese *Mayo", :steps=>"*layout bread *spread mayo on both slices *put on 5 slices of ham *add a slice of cheese *combine all together" ,:description=>"My quick go to lunch", :user_id=> 3, :recipe_type_id=>2)
recipe5=Recipe.create(:name=>"Chicken Dog food", :ingredients=>"*boneless chicken breast *dog food", :steps=>"*boil chicken in pot *once done remove chicken and shread it. *place chicken on top of dog food. *pour some of the stock from the pot on top of food. *allow to cool and then serve" ,:description=>"My ultime favorite way to enjoy my dog food!", :user_id=> 1, :recipe_type_id=>2)
recipe6=Recipe.create(:name=>"Grilled Shrimp Tacos", :ingredients=>"*3 tablespoons butter, melted *2 large garlic cloves, minced *4 limes, cut into quarters *kosher salt *8 6-inch corn tortillas *2 to 3 cups finely shredded green cabbage *jarred green tomatillo salsa", :steps=>"*Step 1 Heat grill to medium-high. In a small bowl, whisk together the sour cream, mayonnaise, milk, and cumin. Set aside. *Step 2 Skewer the shrimp. (If using wood skewers, soak them in water for 10 minutes beforehand.) In a small bowl, combine the butter and garlic. Brush the shrimp with the garlic butter. *Step 3 Place the shrimp on grill with the limes. Cook for about 4 minutes on each side or until the shrimp are opaque and the limes are browned. *Step 4 Remove from grill. Lightly salt the shrimp. *Step 5 Grill the tortillas for 30 seconds on each side, then place inside a paper bag to keep warm. *Step 6 Pull the shrimp off the skewers; divide evenly among the tortillas. Top with the cabbage, sour cream sauce, tomatillo salsa, and a squeeze of grilled lime." ,:description=>"Thread shrimp onto pre-soaked wooden skewers, brush with a finger licking garlic butter, and grill alongside lime wedges. Before serving, toss the tortillas on the grill for 30 seconds on each side to add a smoky char. Serve the tacos with cumin-spiced sour cream, shredded cabbage, and tomatillo salsa.", :user_id=> 4, :recipe_type_id=>2)
recipe7=Recipe.create(:name=>"Avocado, Prosciutto, and Egg Open-Faced Sandwich", :ingredients=>"*2 tablespoons olive oil, plus more for serving *4 large eggs *kosher salt and black pepper *4 large slices country bread, toasted *1 avocado, sliced *2 ounces sliced prosciutto", :steps=>"*Step 1 Heat the oil in a large nonstick skillet over medium heat. Add the eggs and cook, covered, 2 to 4 minutes for slightly runny yolks. Season with ¼ teaspoon each salt and pepper. *Step 2 Dividing evenly, top the bread with the avocado, prosciutto, and eggs. *Step 3 Serve drizzled with additional oil and sprinkled with pepper." ,:description=>"Who says eggs are just for breakfast? This versatile dish works at any time of day.", :user_id=> 2, :recipe_type_id=>2)

# Dinner
recipe8=Recipe.create(:name=>"Smoked Chuck Roast", :ingredients=>"*chuck roast *yellow onion *beef broth *meat rub *foil and foil pan", :steps=>"*rub meat and let rest over night *put on smoker and smoke for 3hrs *put chuck roast in pan with onion and broth and cook for approx. 3hrs or till 165 *cover with foil and cook to 200. *remove and let rest for 30min" ,:description=>"Mouth watering chuck roast that is savory and will you licking your fingers", :user_id=> 3, :recipe_type_id=>3)
recipe9=Recipe.create(:name=>"Chicken and Vegetable PotpieChicken and Vegetable Potpie", :ingredients=>"*1 pound boneless, skinless chicken breasts *1 tablespoon olive oil *2 onions, chopped *4 carrots, diced *3 tablespoons all-purpose flour *½ cup dry white wine *2 cups 1 percent milk *1 10-ounce package frozen peas *1 tablespoon fresh thyme *kosher salt and black pepper *1 9-inch store-bought piecrust, thawed if frozen", :steps=>"*Step 1 Heat oven to 400° F. Cook the chicken in a pot of simmering water until cooked through, 10 to 12 minutes; let cool, then shred. *Step 2 Meanwhile, heat the oil in a saucepan over medium heat. Add the onions and carrots and cook, stirring, until they begin to soften, 6 to 8 minutes (do not let them darken). Sprinkle the flour over the vegetables and cook, stirring, for 1 minute. *Step 3 Add the wine and cook until evaporated, about 5 minutes. Add the milk and simmer until the sauce thickens, 2 to 3 minutes. Stir in the chicken, peas, thyme, ¾ teaspoon salt, and ¼ teaspoon pepper. Transfer to a shallow 1½- to 2-quart baking dish. *Step 4 Lay the crust on top, pressing to seal. Cut several vents in the crust. Place the pot pie on a baking sheet and bake until bubbling and the crust is golden, 30 to 35 minutes" ,:description=>"Use low-fat milk, olive oil, and double the vegetables to give this rustic, down-home comfort food a healthy revamp. To save time on prep without sacrificing the crisp golden-brown exterior, use store-bought piecrust. Just unroll it, lay it over the oven-safe dish, vent, and bake.", :user_id=> 4, :recipe_type_id=>3)
recipe10=Recipe.create(:name=>"Sloppy Joes", :ingredients=>"*ground beef *manwhich *buns *mayo *cheese", :steps=>"*cook beef *add in manwhich *in a skillet butter buns and toast them *put mayo on buns *put cheese on bun and then place manwhich mixture ontop of cheese to melt *combine buns and enjoy!" ,:description=>"Bro night go to! It is simple and messy! I really enjoy mixed with some tator tots in the air fryer and a cold Mnt. Dew!", :user_id=> 3, :recipe_type_id=>3)
recipe11=Recipe.create(:name=>"Smoked Pizza", :ingredients=>"*frozen Pizza *pit boss pellet grill *extra toppings of your choice", :steps=>"*preheat smoker to temp. that is on pizza box *while smoker is heating up add extra toppings of your choice on pizza *place pizza in grill. *after 10 min rotate pizza to make sure for even cooking *cook the remaining time *slice and enjoy" ,:description=>"You seriously never had pizza till you've tried this smoked Pizza recipe. The smoke blends in nicely with with cheese and the crust gets nice and crisp for the perfect Pizza!", :user_id=> 3, :recipe_type_id=>4)

# snacks
recipe12=Recipe.create(:name=>"Kong Treat", :ingredients=>"*dog treats *peanut butter *banana", :steps=>"*put treats in Kong *put banana in Kong *top with peanut butter" ,:description=>"Ultimate Kong Treat. Has peanutbutter to keep you licking, banana for health and then treats to for desert at the end.", :user_id=> 1, :recipe_type_id=>4)
recipe13=Recipe.create(:name=>"chips", :ingredients=>"*owner *bag of chips", :steps=>"*wait for the owner to go to pantry *once in pantry and hear bag being open walk in pantry *give best puppy eyes *then lightly place paw on owners leg *enjoy unlimated chips!" ,:description=>"A bullet proof way to get some free snacks! Just let your looks do the work for you!", :user_id=> 2, :recipe_type_id=>4)
recipe14=Recipe.create(:name=>"Protien Shake", :ingredients=>"*protien powder *ice *milk *fruit of your choice *peanut butter", :steps=>"*put ice in blender *put fruit of your choice in blender *put peanut butter in blender *add protien powder and milk *blend to smoothness you want. *Enjoy!" ,:description=>"A tasty way to get some serious gains!!!!", :user_id=> 3, :recipe_type_id=>4)
recipe15=Recipe.create(:name=>"75 hard coffee", :ingredients=>"*coffee *maple syrup *half and half", :steps=>"*add maple syrup and half and half in cup *with emmerssion blender froth mixture *brew coffee *add frothed mixture to coffe" ,:description=>"*75 hard takes a lot of tasty food away from you. This coffee recipe is one way to stick it to the man. You will forget that your even on a diet!", :user_id=> 3, :recipe_type_id=>4)

# dessert 
recipe16=Recipe.create(:name=>"Dog Ice Cream", :ingredients=>"*banana *peanut butter *honey", :steps=>"*put everything in blender *once blended together place in container and put in freezer" ,:description=>"A sweet treat for your pup on that hot summer day", :user_id=> 2, :recipe_type_id=>5)
recipe17=Recipe.create(:name=>"Lemon drizzle cake", :ingredients=>"*225g unsalted butter *225g caster sugar * 4 eggs *225g self-raising flour *1 lemon, zested *FOR TOPPING *1 1/2 lemons juiced *85g caster sugar", :steps=>"*1. Heat the oven to 180C/160C fan/gas 4 *2. Beat together the butter and caster sugar until pale and creamy, then add the eggs, one at a time, slowly mixing through. *3. Sift in the self-raising flour, then add the lemon zest and mix until well combined. *4. Line a loaf tin (8 x 21cm) with greaseproof paper, then spoon in the mixture and level the top with a spoon. *5. Bake for 45-50 mins until a thin skewer inserted into the centre of the cake comes out clean. *6. While the cake is cooling in its tin, mix together the lemons juice and caster sugar to make the drizzle. *7.Prick the warm cake all over with a skewer or fork, then pour over the drizzle – the juice will sink in and the sugar will form a lovely, crisp topping. *8. Leave in the tin until completely cool, then remove and serve. Will keep in an airtight container for 3-4 days, or freeze for up to 1 month. " ,:description=>"It's difficult not to demolish this classic lemon drizzle in just one sitting, so why not make two at once?", :user_id=> 4, :recipe_type_id=>5)
recipe18=Recipe.create(:name=>"Healthy Yogurt cup", :ingredients=>"*plain greek yogurt *homemade gornola *blueberries *honey", :steps=>"*put yogurt in bowl *add gornola *top with honey and mix *finish off with blueberries" ,:description=>"A way to eat plain greek yogurt that actualy taste good. The honey adds sweetness to counter the sourness of greek yogurt. The gornola and bluberries add great flavor and texture", :user_id=> 4, :recipe_type_id=>5)
recipe19=Recipe.create(:name=>"Salted Oatmeal Cookies With Dark Chocolate", :ingredients=>"*2 cups old-fashioned rolled oats (not quick-cooking) *1 cup all-purpose flour, spooned and leveled *¾ teaspoon baking soda *¼ teaspoon ground cinnamon *2 teaspoons flaky sea salt (such as Maldon) *½ cup (1 stick) unsalted butter, at room temperature *4 tablespoons vegetable shortening *½ cup granulated sugar *½ cup packed light brown sugar *1 large egg *1 teaspoon pure vanilla extract *6 ounces bittersweet chocolate, coarsely chopped", :steps=>"*Step 1 Heat oven to 375° F with the rack in the upper and lower thirds. Line 2 large baking sheets with parchment. *Step 2 Combine the oats, flour, baking soda, cinnamon, and 1 teaspoon of the salt in a medium bowl; set aside. *Step 3 Beat the butter, shortening, granulated sugar, and brown sugar with an electric mixer on medium-high speed until lightly and fluffy, 2 to 3 minutes. Beat in the egg and vanilla. Reduce the mixer speed to low and gradually add the flour mixture, mixing just until combined (do not overmix). Stir in the chocolate. *Step 4 Drop heaping tablespoonfuls of the dough onto the prepared baking sheets, spacing them 2 inches apart. Sprinkle with the remaining 1 teaspoon of salt. *Step 5 Bake, rotating the pans halfway through, until lightly brown around the edges, about 10 to 12 minutes. Cool slightly on the baking sheets, then transfer to a wire rack to cool completely. *Step 6 Storage suggestion:Keep the cookies at room temperature in an airtight container for up to 5 days." ,:description=>"Pillowy oatmeal cookies are stuffed with coarsely chopped dark chocolate chunks and then sprinkled with flaky sea salt (like Maldon) so each bite is the perfect mouthful of salty and sweet. If you need to make the cookies ahead of time, they can be stored at room temperature in an airtight container for up to five days.", :user_id=> 3, :recipe_type_id=>5)













